[package]
name = "aws-credentials-switcher"
version = "1.1.0"
authors = ["Gabriel Plassard <gabriel.plassard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
rust-ini = "0.16.1"
exitcode = "1.1.2"
